MurmurHash: Merge MurmurHash3.cpp to latest release
OS	: Solus 1.2.1 shannon
Kernel	: x86_64 Linux 4.8.2
g++ 	: g++ (Solus) 6.2.0

The FORCE_INLINE preprocessor caused the following errors when compiling
with the g++ (Solus) 6.2.0 compiler :

g++ -ffast-math -O3 -DNDEBUG -mtune=generic -march=x86-64
-ftree-vectorize -g2 -O2 -pipe -fPIC -Wformat -Wformat-secur
ity -fno-omit-frame-pointer -fstack-protector-strong --param
ssp-buffer-size=4 -fexceptions -D_FORTIFY_SOURCE=2 -felim
inate-unused-debug-types -Wno-error -Wp,-D_REENTRANT -Iinclude -Isrc -c
src/third_party/murmurhash/MurmurHash3.cpp -o
src/third_party/murmurhash/MurmurHash3.o
src/third_party/murmurhash/MurmurHash3.cpp:81:23: warning: always_inline
function might not be inlinable [-Wattributes
]
 FORCE_INLINE uint64_t fmix ( uint64_t k )
                       ^~~~
src/third_party/murmurhash/MurmurHash3.cpp:68:23: warning: always_inline
function might not be inlinable [-Wattributes
]
 FORCE_INLINE uint32_t fmix ( uint32_t h )
                       ^~~~
src/third_party/murmurhash/MurmurHash3.cpp:60:23: warning: always_inline
function might not be inlinable [-Wattributes
]
 FORCE_INLINE uint64_t getblock ( const uint64_t * p, int i )
                       ^~~~~~~~
src/third_party/murmurhash/MurmurHash3.cpp:55:23: warning: always_inline
function might not be inlinable [-Wattributes
]
 FORCE_INLINE uint32_t getblock ( const uint32_t * p, int i )
                       ^~~~~~~~
src/third_party/murmurhash/MurmurHash3.cpp: In function â€˜void
MurmurHash3_x86_32(const void*, int, uint32_t, void*)â€™:
src/third_party/murmurhash/MurmurHash3.cpp:55:23: error: inlining failed
in call to always_inline â€˜uint32_t getblock(c
onst uint32_t*, int)â€™: function body can be overwritten at linktime
src/third_party/murmurhash/MurmurHash3.cpp:112:36: note: called from
here
     uint32_t k1 = getblock(blocks,i);
                                    ^
src/third_party/murmurhash/MurmurHash3.cpp:68:23: error: inlining failed
in call to always_inline â€˜uint32_t fmix(uint3
2_t)â€™: function body can be overwritten at link time
 FORCE_INLINE uint32_t fmix ( uint32_t h )
                       ^~~~
src/third_party/murmurhash/MurmurHash3.cpp:143:16: note: called from
here
   h1 = fmix(h1);
                ^
src/third_party/murmurhash/MurmurHash3.cpp:55:23: error: inlining failed
in call to always_inline â€˜uint32_t getblock(c
onst uint32_t*, int)â€™: function body can be overwritten at linktime
 FORCE_INLINE uint32_t getblock ( const uint32_t * p, int i )
                       ^~~~~~~~
src/third_party/murmurhash/MurmurHash3.cpp:112:36: note: called from
here
     uint32_t k1 = getblock(blocks,i);
                                    ^
src/third_party/murmurhash/MurmurHash3.cpp:68:23: error: inlining failed
in call to always_inline â€˜uint32_t fmix(uint3
2_t)â€™: function body can be overwritten at link time
 FORCE_INLINE uint32_t fmix ( uint32_t h )
                       ^~~~
src/third_party/murmurhash/MurmurHash3.cpp:143:16: note: called from
here
   h1 = fmix(h1);
                ^
I did run a successfull compile on another machine of mine running Arch Linux with
g++ (GCC) 6.2.1, however the warnings mentioned were still present.

The reason seems to be in the FORCE_INLINE definition where a inline
specifier is missing before calling the __atribute__((always_inline))
preprocessor.

Merging to the latest MurmurHash3.cpp source has solved this issue.

As for now, I haven't really found any problems with the newer release.

Signed-off-by: CTXz <ctx.xda@gmail.com>